name: Github Pages

# By default, runs if you push to master. keeps your deployed app in sync with master branch.
on:
  schedule: [{cron: "0 10 1 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: read # for committing to gh-pages branch.
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Prepare dependencies
        run: sudo apt-get install -y jq curl

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        run: ./gen.sh

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
